// Sample webhooks to test functionality

export const repoWebhook1 = {
	action: "created",
	repository: {
		id: 123456,
		node_id: "R_kgDOG0",
		name: "example-repo",
		full_name: "octocat/example-repo",
		private: false,
		owner: {
			login: "octocat",
			id: 9876,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://avatars.githubusercontent.com/u/9876?v=4",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/octocat/example-repo",
		description: "This is a test repository",
		fork: false,
		url: "https://api.github.com/repos/octocat/example-repo",
		created_at: "2024-02-03T17:30:20Z",
		updated_at: "2024-02-03T17:30:20Z",
		pushed_at: "2024-02-03T17:30:20Z",
		git_url: "git://github.com/octocat/example-repo.git",
		ssh_url: "git@github.com:octocat/example-repo.git",
		clone_url: "https://github.com/octocat/example-repo.git",
		size: 0,
		stargazers_count: 0,
		watchers_count: 0,
		language: null,
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		visibility: "public",
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: "main",
	},
	organization: {
		login: "octocat",
		id: 9876,
		node_id: "MDEyOk9yZ2FuaXphdGlvbjE=",
		url: "https://api.github.com/orgs/octocat",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
	},
	sender: {
		login: "octocat",
		id: 1234,
		node_id: "MDQ6VXNlcjE=",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
		url: "https://api.github.com/users/octocat",
		html_url: "https://github.com/octocat",
		type: "User",
		site_admin: false,
	},
};

export const repoWebhook2 = {
	action: "created",
	repository: {
		id: 1296269,
		node_id: "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
		name: "Hello-World",
		full_name: "octocat/Hello-World",
		private: false,
		owner: {
			login: "octocat",
			id: 583231,
			node_id: "MDQ6VXNlcjU4MzIzMQ==",
			avatar_url: "https://avatars.githubusercontent.com/u/583231?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			followers_url: "https://api.github.com/users/octocat/followers",
			following_url:
				"https://api.github.com/users/octocat/following{/other_user}",
			gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
			starred_url:
				"https://api.github.com/users/octocat/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/octocat/subscriptions",
			organizations_url: "https://api.github.com/users/octocat/orgs",
			repos_url: "https://api.github.com/users/octocat/repos",
			events_url: "https://api.github.com/users/octocat/events{/privacy}",
			received_events_url:
				"https://api.github.com/users/octocat/received_events",
			type: "User",
			user_view_type: "public",
			site_admin: false,
		},
		html_url: "https://github.com/octocat/Hello-World",
		description: "My first repository on GitHub!",
		fork: false,
		url: "https://api.github.com/repos/octocat/Hello-World",
		forks_url: "https://api.github.com/repos/octocat/Hello-World/forks",
		keys_url: "https://api.github.com/repos/octocat/Hello-World/keys{/key_id}",
		collaborators_url:
			"https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}",
		teams_url: "https://api.github.com/repos/octocat/Hello-World/teams",
		hooks_url: "https://api.github.com/repos/octocat/Hello-World/hooks",
		issue_events_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/events{/number}",
		events_url: "https://api.github.com/repos/octocat/Hello-World/events",
		assignees_url:
			"https://api.github.com/repos/octocat/Hello-World/assignees{/user}",
		branches_url:
			"https://api.github.com/repos/octocat/Hello-World/branches{/branch}",
		tags_url: "https://api.github.com/repos/octocat/Hello-World/tags",
		blobs_url:
			"https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}",
		git_tags_url:
			"https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}",
		git_refs_url:
			"https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}",
		trees_url:
			"https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}",
		statuses_url:
			"https://api.github.com/repos/octocat/Hello-World/statuses/{sha}",
		languages_url: "https://api.github.com/repos/octocat/Hello-World/languages",
		stargazers_url:
			"https://api.github.com/repos/octocat/Hello-World/stargazers",
		contributors_url:
			"https://api.github.com/repos/octocat/Hello-World/contributors",
		subscribers_url:
			"https://api.github.com/repos/octocat/Hello-World/subscribers",
		subscription_url:
			"https://api.github.com/repos/octocat/Hello-World/subscription",
		commits_url:
			"https://api.github.com/repos/octocat/Hello-World/commits{/sha}",
		git_commits_url:
			"https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}",
		comments_url:
			"https://api.github.com/repos/octocat/Hello-World/comments{/number}",
		issue_comment_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}",
		contents_url:
			"https://api.github.com/repos/octocat/Hello-World/contents/{+path}",
		compare_url:
			"https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}",
		merges_url: "https://api.github.com/repos/octocat/Hello-World/merges",
		archive_url:
			"https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}",
		downloads_url: "https://api.github.com/repos/octocat/Hello-World/downloads",
		issues_url:
			"https://api.github.com/repos/octocat/Hello-World/issues{/number}",
		pulls_url:
			"https://api.github.com/repos/octocat/Hello-World/pulls{/number}",
		milestones_url:
			"https://api.github.com/repos/octocat/Hello-World/milestones{/number}",
		notifications_url:
			"https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}",
		labels_url:
			"https://api.github.com/repos/octocat/Hello-World/labels{/name}",
		releases_url:
			"https://api.github.com/repos/octocat/Hello-World/releases{/id}",
		deployments_url:
			"https://api.github.com/repos/octocat/Hello-World/deployments",
		created_at: "2011-01-26T19:01:12Z",
		updated_at: "2025-02-04T22:40:59Z",
		pushed_at: "2024-08-20T23:54:42Z",
		git_url: "git://github.com/octocat/Hello-World.git",
		ssh_url: "git@github.com:octocat/Hello-World.git",
		clone_url: "https://github.com/octocat/Hello-World.git",
		svn_url: "https://github.com/octocat/Hello-World",
		homepage: "",
		size: 1,
		stargazers_count: 2831,
		watchers_count: 2831,
		language: null,
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 2636,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 1539,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [],
		visibility: "public",
		forks: 2636,
		open_issues: 1539,
		watchers: 2831,
		default_branch: "master",
		temp_clone_token: null,
		network_count: 2636,
		subscribers_count: 1733,
	},
	organization: {
		login: "octocat",
		id: 9876,
		node_id: "MDEyOk9yZ2FuaXphdGlvbjE=",
		url: "https://api.github.com/orgs/octocat",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
	},
	sender: {
		login: "octocat",
		id: 1234,
		node_id: "MDQ6VXNlcjE=",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
		url: "https://api.github.com/users/octocat",
		html_url: "https://github.com/octocat",
		type: "User",
		site_admin: false,
	},
};

export const repoWebhook3 = {
	action: "created",
	repository: {
		id: 87654,
		node_id: "R_kgDOG0",
		name: "example-repo",
		full_name: "octocat/example-repo",
		private: false,
		owner: {
			login: "octocat",
			id: 9876,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://avatars.githubusercontent.com/u/9876?v=4",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/octocat/example-repo",
		description: "This is a test repository",
		fork: false,
		url: "https://api.github.com/repos/octocat/example-repo",
		created_at: "2024-02-03T17:30:20Z",
		updated_at: "2024-02-03T17:30:20Z",
		pushed_at: "2024-02-03T17:30:20Z",
		git_url: "git://github.com/octocat/example-repo.git",
		ssh_url: "git@github.com:octocat/example-repo.git",
		clone_url: "https://github.com/octocat/example-repo.git",
		size: 0,
		stargazers_count: 0,
		watchers_count: 0,
		language: null,
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		visibility: "public",
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: "main",
	},
	organization: {
		login: "octocat",
		id: 9876,
		node_id: "MDEyOk9yZ2FuaXphdGlvbjE=",
		url: "https://api.github.com/orgs/octocat",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
	},
	sender: {
		login: "octocat",
		id: 1234,
		node_id: "MDQ6VXNlcjE=",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
		url: "https://api.github.com/users/octocat",
		html_url: "https://github.com/octocat",
		type: "User",
		site_admin: false,
	},
};

export const repoWebhook4 = {
	action: "edited",
	repository: {
		id: 87654,
		node_id: "R_kgDOG0",
		name: "edited-repo",
		full_name: "octocat/example-repo",
		private: false,
		owner: {
			login: "octocat",
			id: 9876,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://avatars.githubusercontent.com/u/9876?v=4",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/octocat/example-repo",
		description: "I edited this repo!",
		fork: false,
		url: "https://api.github.com/repos/octocat/example-repo",
		created_at: "2024-02-03T17:30:20Z",
		updated_at: "2024-02-03T17:30:20Z",
		pushed_at: "2024-02-03T17:30:20Z",
		git_url: "git://github.com/octocat/example-repo.git",
		ssh_url: "git@github.com:octocat/example-repo.git",
		clone_url: "https://github.com/octocat/example-repo.git",
		size: 0,
		stargazers_count: 0,
		watchers_count: 0,
		language: null,
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		visibility: "public",
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: "main",
	},
	organization: {
		login: "octocat",
		id: 9876,
		node_id: "MDEyOk9yZ2FuaXphdGlvbjE=",
		url: "https://api.github.com/orgs/octocat",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
	},
	sender: {
		login: "octocat",
		id: 1234,
		node_id: "MDQ6VXNlcjE=",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
		url: "https://api.github.com/users/octocat",
		html_url: "https://github.com/octocat",
		type: "User",
		site_admin: false,
	},
};

export const issueWebhook1 = {
	action: "edited",
	issue: {
		url: "https://api.github.com/repos/octocat/Hello-World/issues/1",
		repository_url: "https://api.github.com/repos/octocat/Hello-World",
		labels_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/1/labels{/name}",
		comments_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/1/comments",
		events_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/1/events",
		html_url: "https://github.com/octocat/Hello-World/pull/1",
		id: 872858,
		node_id: "MDExOlB1bGxSZXF1ZXN0MTQwOTAw",
		number: 1,
		title: "Edited the issue",
		user: {
			login: "unoju",
			id: 777449,
			node_id: "MDQ6VXNlcjc3NzQ0OQ==",
			avatar_url: "https://avatars.githubusercontent.com/u/777449?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/unoju",
			html_url: "https://github.com/unoju",
			followers_url: "https://api.github.com/users/unoju/followers",
			following_url:
				"https://api.github.com/users/unoju/following{/other_user}",
			gists_url: "https://api.github.com/users/unoju/gists{/gist_id}",
			starred_url: "https://api.github.com/users/unoju/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/unoju/subscriptions",
			organizations_url: "https://api.github.com/users/unoju/orgs",
			repos_url: "https://api.github.com/users/unoju/repos",
			events_url: "https://api.github.com/users/unoju/events{/privacy}",
			received_events_url: "https://api.github.com/users/unoju/received_events",
			type: "User",
			user_view_type: "public",
			site_admin: false,
		},
		labels: [],
		state: "closed",
		locked: false,
		assignee: null,
		assignees: [],
		milestone: null,
		comments: 50,
		created_at: "2011-05-09T19:10:00Z",
		updated_at: "2025-01-22T02:57:48Z",
		closed_at: "2011-05-18T20:00:25Z",
		author_association: "none",
		sub_issues_summary: {
			total: 0,
			completed: 0,
			percent_completed: 0,
		},
		active_lock_reason: null,
		draft: false,
		pull_request: {
			url: "https://api.github.com/repos/octocat/Hello-World/pulls/1",
			html_url: "https://github.com/octocat/Hello-World/pull/1",
			diff_url: "https://github.com/octocat/Hello-World/pull/1.diff",
			patch_url: "https://github.com/octocat/Hello-World/pull/1.patch",
			merged_at: null,
		},
		body: "",
		closed_by: {
			login: "octocat",
			id: 583231,
			node_id: "MDQ6VXNlcjU4MzIzMQ==",
			avatar_url: "https://avatars.githubusercontent.com/u/583231?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			followers_url: "https://api.github.com/users/octocat/followers",
			following_url:
				"https://api.github.com/users/octocat/following{/other_user}",
			gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
			starred_url:
				"https://api.github.com/users/octocat/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/octocat/subscriptions",
			organizations_url: "https://api.github.com/users/octocat/orgs",
			repos_url: "https://api.github.com/users/octocat/repos",
			events_url: "https://api.github.com/users/octocat/events{/privacy}",
			received_events_url:
				"https://api.github.com/users/octocat/received_events",
			type: "User",
			user_view_type: "public",
			site_admin: false,
		},
		reactions: {
			url: "https://api.github.com/repos/octocat/Hello-World/issues/1/reactions",
			total_count: 5,
			"+1": 0,
			"-1": 0,
			laugh: 0,
			hooray: 0,
			confused: 0,
			heart: 1,
			rocket: 4,
			eyes: 0,
		},
		timeline_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/1/timeline",
		performed_via_github_app: null,
		state_reason: null,
	},
	repository: {
		id: 1296269,
		node_id: "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
		name: "Hello-World",
		full_name: "octocat/Hello-World",
		private: false,
		owner: {
			login: "octocat",
			id: 583231,
			node_id: "MDQ6VXNlcjU4MzIzMQ==",
			avatar_url: "https://avatars.githubusercontent.com/u/583231?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			followers_url: "https://api.github.com/users/octocat/followers",
			following_url:
				"https://api.github.com/users/octocat/following{/other_user}",
			gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
			starred_url:
				"https://api.github.com/users/octocat/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/octocat/subscriptions",
			organizations_url: "https://api.github.com/users/octocat/orgs",
			repos_url: "https://api.github.com/users/octocat/repos",
			events_url: "https://api.github.com/users/octocat/events{/privacy}",
			received_events_url:
				"https://api.github.com/users/octocat/received_events",
			type: "User",
			user_view_type: "public",
			site_admin: false,
		},
		html_url: "https://github.com/octocat/Hello-World",
		description: "My first repository on GitHub!",
		fork: false,
		url: "https://api.github.com/repos/octocat/Hello-World",
		forks_url: "https://api.github.com/repos/octocat/Hello-World/forks",
		keys_url: "https://api.github.com/repos/octocat/Hello-World/keys{/key_id}",
		collaborators_url:
			"https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}",
		teams_url: "https://api.github.com/repos/octocat/Hello-World/teams",
		hooks_url: "https://api.github.com/repos/octocat/Hello-World/hooks",
		issue_events_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/events{/number}",
		events_url: "https://api.github.com/repos/octocat/Hello-World/events",
		assignees_url:
			"https://api.github.com/repos/octocat/Hello-World/assignees{/user}",
		branches_url:
			"https://api.github.com/repos/octocat/Hello-World/branches{/branch}",
		tags_url: "https://api.github.com/repos/octocat/Hello-World/tags",
		blobs_url:
			"https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}",
		git_tags_url:
			"https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}",
		git_refs_url:
			"https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}",
		trees_url:
			"https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}",
		statuses_url:
			"https://api.github.com/repos/octocat/Hello-World/statuses/{sha}",
		languages_url: "https://api.github.com/repos/octocat/Hello-World/languages",
		stargazers_url:
			"https://api.github.com/repos/octocat/Hello-World/stargazers",
		contributors_url:
			"https://api.github.com/repos/octocat/Hello-World/contributors",
		subscribers_url:
			"https://api.github.com/repos/octocat/Hello-World/subscribers",
		subscription_url:
			"https://api.github.com/repos/octocat/Hello-World/subscription",
		commits_url:
			"https://api.github.com/repos/octocat/Hello-World/commits{/sha}",
		git_commits_url:
			"https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}",
		comments_url:
			"https://api.github.com/repos/octocat/Hello-World/comments{/number}",
		issue_comment_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}",
		contents_url:
			"https://api.github.com/repos/octocat/Hello-World/contents/{+path}",
		compare_url:
			"https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}",
		merges_url: "https://api.github.com/repos/octocat/Hello-World/merges",
		archive_url:
			"https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}",
		downloads_url: "https://api.github.com/repos/octocat/Hello-World/downloads",
		issues_url:
			"https://api.github.com/repos/octocat/Hello-World/issues{/number}",
		pulls_url:
			"https://api.github.com/repos/octocat/Hello-World/pulls{/number}",
		milestones_url:
			"https://api.github.com/repos/octocat/Hello-World/milestones{/number}",
		notifications_url:
			"https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}",
		labels_url:
			"https://api.github.com/repos/octocat/Hello-World/labels{/name}",
		releases_url:
			"https://api.github.com/repos/octocat/Hello-World/releases{/id}",
		deployments_url:
			"https://api.github.com/repos/octocat/Hello-World/deployments",
		created_at: "2011-01-26T19:01:12Z",
		updated_at: "2025-02-04T22:40:59Z",
		pushed_at: "2024-08-20T23:54:42Z",
		git_url: "git://github.com/octocat/Hello-World.git",
		ssh_url: "git@github.com:octocat/Hello-World.git",
		clone_url: "https://github.com/octocat/Hello-World.git",
		svn_url: "https://github.com/octocat/Hello-World",
		homepage: "",
		size: 1,
		stargazers_count: 2831,
		watchers_count: 2831,
		language: null,
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 2636,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 1539,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [],
		visibility: "public",
		forks: 2636,
		open_issues: 1539,
		watchers: 2831,
		default_branch: "master",
		temp_clone_token: null,
		network_count: 2636,
		subscribers_count: 1733,
	},
	sender: {
		login: "octocat",
		id: 1234,
		node_id: "MDQ6VXNlcjE=",
		avatar_url: "https://avatars.githubusercontent.com/u/1234?v=4",
		url: "https://api.github.com/users/octocat",
		html_url: "https://github.com/octocat",
		type: "User",
		site_admin: false,
	},
};

export const pullRequestWebhook1 = {
	action: "opened",
	number: 128672,
	pull_request: {
		url: "https://api.github.com/repos/octocat/Hello-World/pulls/1",
		id: 140900,
		node_id: "MDExOlB1bGxSZXF1ZXN0MTQwOTAw",
		html_url: "https://github.com/octocat/Hello-World/pull/1",
		diff_url: "https://github.com/octocat/Hello-World/pull/1.diff",
		patch_url: "https://github.com/octocat/Hello-World/pull/1.patch",
		issue_url: "https://api.github.com/repos/octocat/Hello-World/issues/1",
		number: 1,
		state: "closed",
		locked: false,
		title: "Edited README via GitHub",
		user: {
			login: "unoju",
			id: 777449,
			node_id: "MDQ6VXNlcjc3NzQ0OQ==",
			avatar_url: "https://avatars.githubusercontent.com/u/777449?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/unoju",
			html_url: "https://github.com/unoju",
			followers_url: "https://api.github.com/users/unoju/followers",
			following_url:
				"https://api.github.com/users/unoju/following{/other_user}",
			gists_url: "https://api.github.com/users/unoju/gists{/gist_id}",
			starred_url: "https://api.github.com/users/unoju/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/unoju/subscriptions",
			organizations_url: "https://api.github.com/users/unoju/orgs",
			repos_url: "https://api.github.com/users/unoju/repos",
			events_url: "https://api.github.com/users/unoju/events{/privacy}",
			received_events_url: "https://api.github.com/users/unoju/received_events",
			type: "User",
			user_view_type: "public",
			site_admin: false,
		},
		body: "",
		created_at: "2011-05-09T19:10:00Z",
		updated_at: "2025-01-22T02:57:48Z",
		closed_at: "2011-05-18T20:00:25Z",
		merged_at: null,
		merge_commit_sha: "f13731c44acf96f2e5d6f0080f54e09215e36248",
		assignee: null,
		assignees: [],
		requested_reviewers: [],
		requested_teams: [],
		labels: [],
		milestone: null,
		draft: false,
		commits_url:
			"https://api.github.com/repos/octocat/Hello-World/pulls/1/commits",
		review_comments_url:
			"https://api.github.com/repos/octocat/Hello-World/pulls/1/comments",
		review_comment_url:
			"https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}",
		comments_url:
			"https://api.github.com/repos/octocat/Hello-World/issues/1/comments",
		statuses_url:
			"https://api.github.com/repos/octocat/Hello-World/statuses/7044a8a032e85b6ab611033b2ac8af7ce85805b2",
		head: {
			label: "unoju:patch-1",
			ref: "patch-1",
			sha: "7044a8a032e85b6ab611033b2ac8af7ce85805b2",
			user: {
				login: "unoju",
				id: 777449,
				node_id: "MDQ6VXNlcjc3NzQ0OQ==",
				avatar_url: "https://avatars.githubusercontent.com/u/777449?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/unoju",
				html_url: "https://github.com/unoju",
				followers_url: "https://api.github.com/users/unoju/followers",
				following_url:
					"https://api.github.com/users/unoju/following{/other_user}",
				gists_url: "https://api.github.com/users/unoju/gists{/gist_id}",
				starred_url:
					"https://api.github.com/users/unoju/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/unoju/subscriptions",
				organizations_url: "https://api.github.com/users/unoju/orgs",
				repos_url: "https://api.github.com/users/unoju/repos",
				events_url: "https://api.github.com/users/unoju/events{/privacy}",
				received_events_url:
					"https://api.github.com/users/unoju/received_events",
				type: "User",
				user_view_type: "public",
				site_admin: false,
			},
			repo: {
				id: 1724195,
				node_id: "MDEwOlJlcG9zaXRvcnkxNzI0MTk1",
				name: "Hello-World",
				full_name: "unoju/Hello-World",
				private: false,
				owner: {
					login: "unoju",
					id: 777449,
					node_id: "MDQ6VXNlcjc3NzQ0OQ==",
					avatar_url: "https://avatars.githubusercontent.com/u/777449?v=4",
					gravatar_id: "",
					url: "https://api.github.com/users/unoju",
					html_url: "https://github.com/unoju",
					followers_url: "https://api.github.com/users/unoju/followers",
					following_url:
						"https://api.github.com/users/unoju/following{/other_user}",
					gists_url: "https://api.github.com/users/unoju/gists{/gist_id}",
					starred_url:
						"https://api.github.com/users/unoju/starred{/owner}{/repo}",
					subscriptions_url: "https://api.github.com/users/unoju/subscriptions",
					organizations_url: "https://api.github.com/users/unoju/orgs",
					repos_url: "https://api.github.com/users/unoju/repos",
					events_url: "https://api.github.com/users/unoju/events{/privacy}",
					received_events_url:
						"https://api.github.com/users/unoju/received_events",
					type: "User",
					user_view_type: "public",
					site_admin: false,
				},
				html_url: "https://github.com/unoju/Hello-World",
				description: "This your first repo!",
				fork: true,
				url: "https://api.github.com/repos/unoju/Hello-World",
				forks_url: "https://api.github.com/repos/unoju/Hello-World/forks",
				keys_url:
					"https://api.github.com/repos/unoju/Hello-World/keys{/key_id}",
				collaborators_url:
					"https://api.github.com/repos/unoju/Hello-World/collaborators{/collaborator}",
				teams_url: "https://api.github.com/repos/unoju/Hello-World/teams",
				hooks_url: "https://api.github.com/repos/unoju/Hello-World/hooks",
				issue_events_url:
					"https://api.github.com/repos/unoju/Hello-World/issues/events{/number}",
				events_url: "https://api.github.com/repos/unoju/Hello-World/events",
				assignees_url:
					"https://api.github.com/repos/unoju/Hello-World/assignees{/user}",
				branches_url:
					"https://api.github.com/repos/unoju/Hello-World/branches{/branch}",
				tags_url: "https://api.github.com/repos/unoju/Hello-World/tags",
				blobs_url:
					"https://api.github.com/repos/unoju/Hello-World/git/blobs{/sha}",
				git_tags_url:
					"https://api.github.com/repos/unoju/Hello-World/git/tags{/sha}",
				git_refs_url:
					"https://api.github.com/repos/unoju/Hello-World/git/refs{/sha}",
				trees_url:
					"https://api.github.com/repos/unoju/Hello-World/git/trees{/sha}",
				statuses_url:
					"https://api.github.com/repos/unoju/Hello-World/statuses/{sha}",
				languages_url:
					"https://api.github.com/repos/unoju/Hello-World/languages",
				stargazers_url:
					"https://api.github.com/repos/unoju/Hello-World/stargazers",
				contributors_url:
					"https://api.github.com/repos/unoju/Hello-World/contributors",
				subscribers_url:
					"https://api.github.com/repos/unoju/Hello-World/subscribers",
				subscription_url:
					"https://api.github.com/repos/unoju/Hello-World/subscription",
				commits_url:
					"https://api.github.com/repos/unoju/Hello-World/commits{/sha}",
				git_commits_url:
					"https://api.github.com/repos/unoju/Hello-World/git/commits{/sha}",
				comments_url:
					"https://api.github.com/repos/unoju/Hello-World/comments{/number}",
				issue_comment_url:
					"https://api.github.com/repos/unoju/Hello-World/issues/comments{/number}",
				contents_url:
					"https://api.github.com/repos/unoju/Hello-World/contents/{+path}",
				compare_url:
					"https://api.github.com/repos/unoju/Hello-World/compare/{base}...{head}",
				merges_url: "https://api.github.com/repos/unoju/Hello-World/merges",
				archive_url:
					"https://api.github.com/repos/unoju/Hello-World/{archive_format}{/ref}",
				downloads_url:
					"https://api.github.com/repos/unoju/Hello-World/downloads",
				issues_url:
					"https://api.github.com/repos/unoju/Hello-World/issues{/number}",
				pulls_url:
					"https://api.github.com/repos/unoju/Hello-World/pulls{/number}",
				milestones_url:
					"https://api.github.com/repos/unoju/Hello-World/milestones{/number}",
				notifications_url:
					"https://api.github.com/repos/unoju/Hello-World/notifications{?since,all,participating}",
				labels_url:
					"https://api.github.com/repos/unoju/Hello-World/labels{/name}",
				releases_url:
					"https://api.github.com/repos/unoju/Hello-World/releases{/id}",
				deployments_url:
					"https://api.github.com/repos/unoju/Hello-World/deployments",
				created_at: "2011-05-09T19:07:52Z",
				updated_at: "2013-12-16T11:24:37Z",
				pushed_at: "2018-11-30T08:29:27Z",
				git_url: "git://github.com/unoju/Hello-World.git",
				ssh_url: "git@github.com:unoju/Hello-World.git",
				clone_url: "https://github.com/unoju/Hello-World.git",
				svn_url: "https://github.com/unoju/Hello-World",
				homepage: "repo 1",
				size: 305,
				stargazers_count: 1,
				watchers_count: 1,
				language: null,
				has_issues: false,
				has_projects: true,
				has_downloads: true,
				has_wiki: true,
				has_pages: false,
				has_discussions: false,
				forks_count: 0,
				mirror_url: null,
				archived: false,
				disabled: false,
				open_issues_count: 1,
				license: null,
				allow_forking: true,
				is_template: false,
				web_commit_signoff_required: false,
				topics: [],
				visibility: "public",
				forks: 0,
				open_issues: 1,
				watchers: 1,
				default_branch: "master",
			},
		},
		base: {
			label: "octocat:master",
			ref: "master",
			sha: "553c2077f0edc3d5dc5d17262f6aa498e69d6f8e",
			user: {
				login: "octocat",
				id: 583231,
				node_id: "MDQ6VXNlcjU4MzIzMQ==",
				avatar_url: "https://avatars.githubusercontent.com/u/583231?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/octocat",
				html_url: "https://github.com/octocat",
				followers_url: "https://api.github.com/users/octocat/followers",
				following_url:
					"https://api.github.com/users/octocat/following{/other_user}",
				gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
				starred_url:
					"https://api.github.com/users/octocat/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/octocat/subscriptions",
				organizations_url: "https://api.github.com/users/octocat/orgs",
				repos_url: "https://api.github.com/users/octocat/repos",
				events_url: "https://api.github.com/users/octocat/events{/privacy}",
				received_events_url:
					"https://api.github.com/users/octocat/received_events",
				type: "User",
				user_view_type: "public",
				site_admin: false,
			},
			repo: {
				id: 1296269,
				node_id: "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
				name: "Hello-World",
				full_name: "octocat/Hello-World",
				private: false,
				owner: {
					login: "octocat",
					id: 583231,
					node_id: "MDQ6VXNlcjU4MzIzMQ==",
					avatar_url: "https://avatars.githubusercontent.com/u/583231?v=4",
					gravatar_id: "",
					url: "https://api.github.com/users/octocat",
					html_url: "https://github.com/octocat",
					followers_url: "https://api.github.com/users/octocat/followers",
					following_url:
						"https://api.github.com/users/octocat/following{/other_user}",
					gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
					starred_url:
						"https://api.github.com/users/octocat/starred{/owner}{/repo}",
					subscriptions_url:
						"https://api.github.com/users/octocat/subscriptions",
					organizations_url: "https://api.github.com/users/octocat/orgs",
					repos_url: "https://api.github.com/users/octocat/repos",
					events_url: "https://api.github.com/users/octocat/events{/privacy}",
					received_events_url:
						"https://api.github.com/users/octocat/received_events",
					type: "User",
					user_view_type: "public",
					site_admin: false,
				},
				html_url: "https://github.com/octocat/Hello-World",
				description: "My first repository on GitHub!",
				fork: false,
				url: "https://api.github.com/repos/octocat/Hello-World",
				forks_url: "https://api.github.com/repos/octocat/Hello-World/forks",
				keys_url:
					"https://api.github.com/repos/octocat/Hello-World/keys{/key_id}",
				collaborators_url:
					"https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}",
				teams_url: "https://api.github.com/repos/octocat/Hello-World/teams",
				hooks_url: "https://api.github.com/repos/octocat/Hello-World/hooks",
				issue_events_url:
					"https://api.github.com/repos/octocat/Hello-World/issues/events{/number}",
				events_url: "https://api.github.com/repos/octocat/Hello-World/events",
				assignees_url:
					"https://api.github.com/repos/octocat/Hello-World/assignees{/user}",
				branches_url:
					"https://api.github.com/repos/octocat/Hello-World/branches{/branch}",
				tags_url: "https://api.github.com/repos/octocat/Hello-World/tags",
				blobs_url:
					"https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}",
				git_tags_url:
					"https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}",
				git_refs_url:
					"https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}",
				trees_url:
					"https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}",
				statuses_url:
					"https://api.github.com/repos/octocat/Hello-World/statuses/{sha}",
				languages_url:
					"https://api.github.com/repos/octocat/Hello-World/languages",
				stargazers_url:
					"https://api.github.com/repos/octocat/Hello-World/stargazers",
				contributors_url:
					"https://api.github.com/repos/octocat/Hello-World/contributors",
				subscribers_url:
					"https://api.github.com/repos/octocat/Hello-World/subscribers",
				subscription_url:
					"https://api.github.com/repos/octocat/Hello-World/subscription",
				commits_url:
					"https://api.github.com/repos/octocat/Hello-World/commits{/sha}",
				git_commits_url:
					"https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}",
				comments_url:
					"https://api.github.com/repos/octocat/Hello-World/comments{/number}",
				issue_comment_url:
					"https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}",
				contents_url:
					"https://api.github.com/repos/octocat/Hello-World/contents/{+path}",
				compare_url:
					"https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}",
				merges_url: "https://api.github.com/repos/octocat/Hello-World/merges",
				archive_url:
					"https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}",
				downloads_url:
					"https://api.github.com/repos/octocat/Hello-World/downloads",
				issues_url:
					"https://api.github.com/repos/octocat/Hello-World/issues{/number}",
				pulls_url:
					"https://api.github.com/repos/octocat/Hello-World/pulls{/number}",
				milestones_url:
					"https://api.github.com/repos/octocat/Hello-World/milestones{/number}",
				notifications_url:
					"https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}",
				labels_url:
					"https://api.github.com/repos/octocat/Hello-World/labels{/name}",
				releases_url:
					"https://api.github.com/repos/octocat/Hello-World/releases{/id}",
				deployments_url:
					"https://api.github.com/repos/octocat/Hello-World/deployments",
				created_at: "2011-01-26T19:01:12Z",
				updated_at: "2025-02-06T13:41:31Z",
				pushed_at: "2024-08-20T23:54:42Z",
				git_url: "git://github.com/octocat/Hello-World.git",
				ssh_url: "git@github.com:octocat/Hello-World.git",
				clone_url: "https://github.com/octocat/Hello-World.git",
				svn_url: "https://github.com/octocat/Hello-World",
				homepage: "",
				size: 1,
				stargazers_count: 2837,
				watchers_count: 2837,
				language: null,
				has_issues: true,
				has_projects: true,
				has_downloads: true,
				has_wiki: true,
				has_pages: false,
				has_discussions: false,
				forks_count: 2648,
				mirror_url: null,
				archived: false,
				disabled: false,
				open_issues_count: 1540,
				license: null,
				allow_forking: true,
				is_template: false,
				web_commit_signoff_required: false,
				topics: [],
				visibility: "public",
				forks: 2648,
				open_issues: 1540,
				watchers: 2837,
				default_branch: "master",
			},
		},
		_links: {
			self: {
				href: "https://api.github.com/repos/octocat/Hello-World/pulls/1",
			},
			html: {
				href: "https://github.com/octocat/Hello-World/pull/1",
			},
			issue: {
				href: "https://api.github.com/repos/octocat/Hello-World/issues/1",
			},
			comments: {
				href: "https://api.github.com/repos/octocat/Hello-World/issues/1/comments",
			},
			review_comments: {
				href: "https://api.github.com/repos/octocat/Hello-World/pulls/1/comments",
			},
			review_comment: {
				href: "https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}",
			},
			commits: {
				href: "https://api.github.com/repos/octocat/Hello-World/pulls/1/commits",
			},
			statuses: {
				href: "https://api.github.com/repos/octocat/Hello-World/statuses/7044a8a032e85b6ab611033b2ac8af7ce85805b2",
			},
		},
		author_association: "none",
		auto_merge: null,
		active_lock_reason: null,
		merged: false,
		mergeable: false,
		rebaseable: false,
		mergeable_state: "dirty",
		merged_by: null,
		comments: 50,
		review_comments: 14,
		maintainer_can_modify: false,
		commits: 1,
		additions: 6,
		deletions: 1,
		changed_files: 1,
		reactions: {
			url: "https://api.github.com/repos/octocat/Hello-World/issues/1/reactions",
			total_count: 5,
			"+1": 0,
			"-1": 0,
			laugh: 0,
			hooray: 0,
			confused: 0,
			heart: 1,
			rocket: 4,
			eyes: 0,
		},
	},
	repository: {
		id: 123456,
		node_id: "R_kgDOG0",
		name: "example-repo",
		full_name: "octocat/example-repo",
		private: false,
		owner: {
			login: "octocat",
			id: 9876,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://avatars.githubusercontent.com/u/9876?v=4",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/octocat/example-repo",
		description: "This is a test repository",
		fork: false,
		url: "https://api.github.com/repos/octocat/example-repo",
		created_at: "2024-02-03T17:30:20Z",
		updated_at: "2024-02-03T17:30:20Z",
		pushed_at: "2024-02-03T17:30:20Z",
		git_url: "git://github.com/octocat/example-repo.git",
		ssh_url: "git@github.com:octocat/example-repo.git",
		clone_url: "https://github.com/octocat/example-repo.git",
		size: 0,
		stargazers_count: 0,
		watchers_count: 0,
		language: null,
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		visibility: "public",
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: "main",
	},
	sender: {
		login: "octocat",
		id: 9876,
		node_id: "XXXXXXXXXXX=",
		avatar_url: "https://avatars.githubusercontent.com/u/9876?v=4",
		gravatar_id: "",
		url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		html_url: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
		followers_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		following_url:
			"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{/other_user}",
		gists_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{/gist_id}",
		starred_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{/owner}{/repo}",
		subscriptions_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		organizations_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		repos_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		events_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{/privacy}",
		received_events_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		type: "User",
		site_admin: false,
	},
};

export const issueCommentWebhook1 = {
	action: "edited",
	issue: {
		url: "https://api.github.com/repos/octocat/Hello-World/issues/1",
		id: 87236,
		node_id: "MDU6SXNzdWUx",
		number: 1,
		title: "Found a bug",
		user: {
			login: "octocat",
			id: 1,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://github.com/images/error/octocat_happy.gif",
			url: "https://api.github.com/users/octocat",
		},
		reactions: {
			url: "https://api.github.com/repos/octocat/Hello-World/issues/1/reactions",
			total_count: 5,
			plusone: 0,
			minusone: 0,
			laugh: 0,
			hooray: 0,
			confused: 0,
			heart: 1,
			rocket: 4,
			eyes: 0,
		},
		state: "open",
		locked: false,
		assignee: null,
		assignees: [],
		milestone: null,
		comments: 1,
		created_at: "2024-02-05T15:00:00Z",
		updated_at: "2024-02-05T15:00:00Z",
		closed_at: null,
		author_association: "owner",
		body: "I'm having a problem with this.",
	},
	comment: {
		url: "https://api.github.com/repos/octocat/Hello-World/issues/comments/1",
		html_url: "https://github.com/octocat/Hello-World/issues/1#issuecomment-1",
		issue_url: "https://api.github.com/repos/octocat/Hello-World/issues/1",
		id: 21876231876,
		node_id: "MDEyOklzc3VlQ29tbWVudDE=",
		user: {
			login: "octocat",
			id: 1,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://github.com/images/error/octocat_happy.gif",
			url: "https://api.github.com/users/octocat",
			type: "User",
		},
		created_at: "2024-02-05T15:00:00Z",
		updated_at: "2024-02-05T15:00:00Z",
		author_association: "owner",
		body: "Me too",
		created_by: {
			login: "octocat",
			id: 1,
			node_id: "XXXXXXXXXXX=",
			avatar_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
			url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		},
	},
	repository: {
		id: 1296269,
		node_id: "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
		name: "Hello-World",
		full_name: "octocat/Hello-World",
		owner: {
			login: "octocat",
			id: 1,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://github.com/images/error/octocat_happy.gif",
			url: "https://api.github.com/users/octocat",
		},
		private: false,
		description: "This is your first repository",
		fork: false,
		url: "https://api.github.com/repos/octocat/Hello-World",
		created_at: "2024-02-05T15:00:00Z",
		updated_at: "2024-02-05T15:00:00Z",
		pushed_at: "2024-02-05T15:00:00Z",
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
	},
	sender: {
		login: "octocat",
		id: 1,
		node_id: "MDQ6VXNlcjE=",
		avatar_url: "https://github.com/images/error/octocat_happy.gif",
		url: "https://api.github.com/users/octocat",
	},
};